version: '3'
services:
  youtrack:
    container_name: youtrack
    build:
      context: docker/youtrack
    ports:
      - 8080:8080
    volumes:
      - ./data/youtrack/data:/opt/youtrack/data
      - ./data/youtrack/conf:/opt/youtrack/conf
      - ./data/youtrack/logs:/opt/youtrack/logs
      - ./data/youtrack/backups:/opt/youtrack/backups
  upsource:
    build:
      context: docker/upsource
    container_name: upsource
    volumes:
      - ./data/upsource/data:/opt/upsource/data
      - ./data/upsource/conf:/opt/upsource/conf
      - ./data/upsource/logs:/opt/upsource/logs
      - ./data/upsource/backups:/opt/upsource/backups
    ports:
      - 8081:8080
  teamcity:
    build:
      context: docker/teamcity
    container_name: teamcity
    volumes:
      - ./data/teamcity/datadir:/data/teamcity_server/datadir
      - ./data/teamcity/logs:/opt/teamcity/logs
    ports:
      - 8082:8111
  hub:
    build:
      context: docker/hub
    container_name: hub
    volumes:
      - ./data/hub/data:/opt/hub/data
      - ./data/hub/conf:/opt/hub/conf
      - ./data/hub/logs:/opt/hub/logs
      - ./data/hub/backups:/opt/hub/backups
    ports:
      - 8083:8080

